workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - build
  - deploy

#Primarily concerned with setting up micromamba for the appropriate platforms
#All the build requirements excepting some compiler magic is there
.bash_before: &bash_before
  - export PATH=/projects/gcc-8.3.0/toolset/gcc-8.3.0/bin:$PATH       
  - export LD_LIBRARY_PATH=/projects/gcc-8.3.0/toolset/gcc-8.3.0/lib64
  - export MAMBA_ROOT_PREFIX="$CI_PROJECT_DIR/tools/micromamba"
  - source ./ci/setup_mamba.sh
  - micromamba activate saline_39

.powershell_before: &powershell_before
  - $env:MAMBA_ROOT_PREFIX="$CI_PROJECT_DIR/tools/micromamba"
  - . $CI_PROJECT_DIR/ci/setup_mamba.ps1
  - micromamba activate saline_39

build_macos:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
    - when: always
  allow_failure: true
  tags:
    - macOS
  before_script:
    - *bash_before
  script:
    - pip install delocate
    - cmake -S $CI_PROJECT_DIR -B "$CI_PROJECT_DIR/build" -DCMAKE_BUILD_TYPE=RELEASE
      -Dsaline_ENABLE_Fortran=ON -DCMAKE_Fortran_FLAGS:STRING="-ffree-line-length-none"
      -Dsaline_ENABLE_Python=ON
    - cmake --build "$CI_PROJECT_DIR/build"
    - ctest --test-dir "$CI_PROJECT_DIR/build"
    - cmake --install build --prefix install
    - delocate-wheel -w ${CI_PROJECT_DIR}/install/wheelhouse ${CI_PROJECT_DIR}/build/src/python/dist/SalinePy*.whl
  artifacts:
    name: darwin_x86
    expire_in: 1 week
    paths:
      - install

build_windows:
  stage: build
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
    - when: always
  tags:
    - windows
  before_script:
    - *powershell_before
  script:
    - pip install delvewheel
    - cmake
      -S $CI_PROJECT_DIR
      -B build
      -Dsaline_ENABLE_Fortran=OFF
      -Dsaline_ENABLE_Python=ON
      -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE
    - cmake --build build --target ALL_BUILD --config RELEASE
    - ctest --build-config RELEASE --test-dir build
    - cmake --install build --prefix install
    - $WHL_FILE = (Get-Item ${CI_PROJECT_DIR}\build\src\python\dist\*.whl).FullName
    - delvewheel repair -w ${CI_PROJECT_DIR}/install/wheelhouse ${WHL_FILE}
  artifacts:
    name: windows_x86
    expire_in: 1 week
    paths:
      - install

build_linux:
  stage: build
  rules:
    - when: always
  tags:
    - linux
  before_script:
    - *bash_before
  script:
    - pip install auditwheel
    - pip install patchelf
    - cmake -S $CI_PROJECT_DIR -B build -DCMAKE_BUILD_TYPE=RELEASE
      -Dsaline_ENABLE_Fortran=ON -DCMAKE_Fortran_FLAGS:STRING="-ffree-line-length-none"
      -Dsaline_ENABLE_Python=ON
      -DCMAKE_CXX_COMPILER=/projects/gcc-8.3.0/toolset/gcc-8.3.0/bin/g++
      -DCMAKE_Fortran_COMPILER=/projects/gcc-8.3.0/toolset/gcc-8.3.0/bin/gfortran
    - cmake --build build
    - ctest --test-dir build
    - cmake --install build --prefix install
    - auditwheel repair -w ${CI_PROJECT_DIR}/install/wheelhouse --plat manylinux_2_24_x86_64 ${CI_PROJECT_DIR}/build/src/python/dist/SalinePy*.whl
  artifacts:
    name: linux_x86
    expire_in: 1 week
    paths:
      - install

        #deploy_staging:
        #  stage: deploy
        #  tags:
        #    - linux
        #    - gcc
        #    - mamba
        #  rules:
        #    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
        #      when: never
        #    - when: manual
        #  needs:
        #    - build_linux
        #    - build_macos
        #    - build_windows
        #  before_script:
        #    - *bash_before
        #  script:
      #- tar -czvf linux_x86.tar.gz ./install
      #- 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file darwin_x86.tar.gz  "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/0.0.1/darwin_x86.tar.gz"'
      #- WHL_FILE=${CI_PROJECT_DIR}/build/src/python/dist/SalinePy*.whl
      #- TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi ${WHL_FILE}
        #
      #- tar -czvf windows_x86.tar.gz ./install
      #- Invoke-RestMethod -Headers @{ "JOB-TOKEN"="$CI_JOB_TOKEN" } -InFile windows_x86.tar.gz -uri "${CI_API_V4_URL}/projects/5955/packages/generic/my_package/0.0.1/windows_x86.tar.gz" -Method put
      #- twine upload -u gitlab-ci-token -p ${CI_JOB_TOKEN} --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi ${CI_PROJECT_DIR}\build\src\python\dist\${WHL_FILE}
        #
      #- tar -czvf linux_x86.tar.gz ./install
      #- 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file linux_x86.tar.gz "${CI_API_V4_URL}/projects/5955/packages/generic/my_package/0.0.1/linux_x86.tar.gz"'
      #- WHL_FILE=${CI_PROJECT_DIR}/build/src/python/dist/SalinePy*.whl
      #- TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi ${WHL_FILE}
