!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: Tue Aug 27 16:55:33 EDT 2024
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module data_store_I
use, intrinsic :: ISO_C_BINDING
interface
logical(C_BOOL) function f_Data_Store_valid(Data_Store_ptr, id ) BIND(C,name="Data_Store_valid")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: Data_Store_ptr;
    integer(C_INT) :: id;
end function
integer(C_INT) function f_Data_Store_size(Data_Store_ptr ) BIND(C,name="Data_Store_size")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: Data_Store_ptr;
end function
subroutine f_Data_Store_destroy(this) BIND(C,name="Data_Store_destroy")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: this;
end subroutine
end interface
end module data_store_I
