!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: Tue Aug 27 16:55:33 EDT 2024
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module default_data_store_I
use, intrinsic :: ISO_C_BINDING
interface
subroutine f_Default_Data_Store_load(Default_Data_Store_ptr, path ) BIND(C,name="Default_Data_Store_load")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: Default_Data_Store_ptr;
    character(C_CHAR) :: path;
end subroutine
type(C_PTR) function f_Default_Data_Store_initialize( )BIND(C,name="Default_Data_Store_initialize")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR) :: Default_Data_Store_ptr;
end function
subroutine f_Default_Data_Store_destroy(this) BIND(C,name="Default_Data_Store_destroy")
    use,intrinsic :: ISO_C_BINDING
    implicit none
    type(C_PTR), value :: this;
end subroutine
end interface
end module default_data_store_I
