!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: Wed Mar 29 11:07:39 EDT 2023
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module r_kister_data_store_M
use, intrinsic :: ISO_C_BINDING
use r_kister_data_store_I
use Data_Store_M
type , extends(Data_Store) :: R_Kister_Data_Store
    contains
    procedure, pass(this) :: load => R_Kister_Data_Store_load
    procedure, pass(this) :: initialize => R_Kister_Data_Store_initialize
    procedure, pass(this) :: destroy => R_Kister_Data_Store_destroy
end type R_Kister_Data_Store
contains
subroutine R_Kister_Data_Store_load(this, rkpath, dfpath)
    implicit none
    class(R_Kister_Data_Store)::this
    character(len=*)::rkpath
    character(len=*)::dfpath
    call f_R_Kister_Data_Store_load(this%instance_ptr, rkpath//C_NULL_CHAR,dfpath//C_NULL_CHAR)
end subroutine
subroutine R_Kister_Data_Store_initialize(this)
    implicit none
    class(R_Kister_Data_Store) :: this
    this%instance_ptr = f_R_Kister_Data_Store_initialize()
end subroutine
subroutine R_Kister_Data_Store_destroy(this)
    implicit none
    class(R_Kister_Data_Store) :: this
    call f_R_Kister_Data_Store_destroy(this%instance_ptr)
    this%instance_ptr = C_NULL_PTR
end subroutine
end module r_kister_data_store_M
