/*!
* This file has been dynamically generated by Class Interface Xml (CIX) 
* DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
* If changes need to occur, modify the appropriate CIX xml file
* Date Generated: Tue Aug 27 16:55:33 EDT 2024
* If any issues are experiences with this generated file that cannot be fixed
* with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
*/
#ifndef R_KISTER_DATA_STOREINTERFACE_H
#define R_KISTER_DATA_STOREINTERFACE_H
#include "r_kister_data_store.hh"
using namespace saline;
#ifdef __cplusplus
extern "C" {
#endif
void R_Kister_Data_Store_load(void * R_Kister_Data_Store_ptr,char* rkdens,char* rkvisc,char* dfpath);
void* R_Kister_Data_Store_initialize();
void R_Kister_Data_Store_destroy(void * R_Kister_Data_Store_ptr);
#ifdef __cplusplus
}
#endif
#endif /* R_KISTER_DATA_STOREINTERFACE_H */
