#This file uses generator expression from CMake to set up all the paths and
#files. The general framework would work for manual use but the expression would
# need to be replaced with equivalent values.

from setuptools import Extension, setup
import platform

#TODO I think this can be replaced by some Cmake
def get_extra_link_args():
    if platform.system() == 'Windows':
        return []
    else:
        return ["-Wl,-rpath=$ORIGIN/lib/."]

#Nominally this is just one directory. This just  ensures it doesn't have to be.
incl_dirs = "$<TARGET_PROPERTY:saline-cpp,INCLUDE_DIRECTORIES>".split(";")
ext_obj_list = "$<TARGET_OBJECTS:saline-cpp>".split(";")

ext_mod = Extension("_SalinePy",
        #Generated by Swig during configuration
        sources            = ["SalinePy_wrap.cxx"],
        #Header files for the Saline C++ code
        include_dirs       = incl_dirs,
        extra_objects      = ext_obj_list,
        #Arguments for helping the linker and runtime loader
        extra_link_args = get_extra_link_args(),
        )

setup(
        name            = "SalinePy",
        python_requires = ">3.8",
        version         = "0.0.1",
        ext_modules     = [ext_mod],
        py_modules      = ["SalinePy"],
    )
