#This file uses generator expression from CMake to set up all the paths and
#files. The general framework would work for manual use but the expression would
# need to be replaced with equivalent values.

from setuptools import Extension, setup
import platform

#TODO I think this can be replaced by some Cmake
def get_extra_compile_args():
    if platform.system() == 'Windows':
        return []
    else:
        return ["-std=c++11"]

def get_extra_link_args():
    if platform.system() == 'Windows':
        return []
    else:
        return ["-Wl,-rpath,$ORIGIN/lib/."]

# read the contents of your README file
from pathlib import Path
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

#Nominally this is just one directory. This just  ensures it doesn't have to be.
incl_dirs = "$<TARGET_PROPERTY:saline-cpp,INCLUDE_DIRECTORIES>".split(";")
incl_dirs.extend("$<TARGET_PROPERTY:SalinePy,INTERFACE_INCLUDE_DIRECTORIES>".split(";"))
ext_obj_list = "$<TARGET_OBJECTS:saline-cpp>".split(";")

ext_mod = Extension("_SalinePy",
        #Generated by Swig during configuration
        sources            = ["SalinePy_wrap.cxx"],
        #Header files for the Saline C++ code
        include_dirs       = incl_dirs,
        extra_objects      = ext_obj_list,
        extra_compile_args = get_extra_compile_args(), 
        #Arguments for helping the linker and runtime loader
        extra_link_args    = get_extra_link_args(),
        )

setup(
        name            = "SalinePy",
        version         = "$<TARGET_PROPERTY:saline,VERSION>",
        python_requires = ">3.8",
        py_modules      = ["SalinePy"],
        author          = "Shane C. Henderson",
        author_email    = "hendersonsc@ornl",
        url             = "https://code.ornl.gov/NEAMS/saline",
        long_description= long_description,
        long_description_content_type="text/markdown",
        ext_modules     = [ext_mod],
        license_files   = "LICENSE"
    )
#setup (name = 'wasp',
#       version = "${${PROJECT_NAME}_VERSION}",
#       description = """${${PROJECT_NAME}_FULL_VERSION}""",
#       author ="Shane Henderson, Robert A. Lefebvre",
#       author_email="hendersonsc@ornl.gov, lefebvrera@ornl.gov"
#       url="https://code.ornl.gov/neams-workbench/wasp",
#       ext_modules = [wasp_module],
#       py_modules = ["wasp"],
#       long_description=long_description,
#       long_description_content_type='text/markdown',
#       license_files = "LICENSE"
#       )
