!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: Thu May 21 19:31:20 EDT 2020
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module data_store_M
use, intrinsic :: ISO_C_BINDING
use data_store_I
type Data_Store
    type(C_PTR) :: instance_ptr=C_NULL_PTR
    contains
    procedure, pass(this) :: valid => Data_Store_valid
    procedure, pass(this) :: size => Data_Store_size
    procedure, pass(this) :: destroy => Data_Store_destroy
end type Data_Store
contains
function Data_Store_valid(this, id) result(result2Return)
    implicit none
    class(Data_Store)::this
    integer(C_INT)::id
    logical(C_BOOL):: result2Return
    result2Return=f_Data_Store_valid(this%instance_ptr, id)
end function
function Data_Store_size(this) result(result2Return)
    implicit none
    class(Data_Store)::this
    integer(C_INT):: result2Return
    result2Return=f_Data_Store_size(this%instance_ptr)
end function
subroutine Data_Store_destroy(this)
    implicit none
    class(Data_Store) :: this
    call f_Data_Store_destroy(this%instance_ptr)
    this%instance_ptr = C_NULL_PTR
end subroutine
end module data_store_M
