/*!
* This file has been dynamically generated by Class Interface Xml (CIX) 
* DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
* If changes need to occur, modify the appropriate CIX xml file
* Date Generated: Thu May 21 19:31:20 EDT 2020
* If any issues are experiences with this generated file that cannot be fixed
* with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
*/
#include <string.h>
#include "data_storeInterface.h"
using namespace saline;
bool Data_Store_valid(void * Data_Store_ptr,int * id)
{
    return ((Data_Store*)Data_Store_ptr)->valid(*id);
}

int Data_Store_size(void * Data_Store_ptr)
{
    return ((Data_Store*)Data_Store_ptr)->size();
}

void Data_Store_destroy(void * Data_Store_ptr)
{
    delete (Data_Store*)Data_Store_ptr;
}

