/*!
* This file has been dynamically generated by Class Interface Xml (CIX) 
* DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
* If changes need to occur, modify the appropriate CIX xml file
* Date Generated: Wed Jan 13 15:03:22 EST 2021
* If any issues are experiences with this generated file that cannot be fixed
* with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
*/
#ifndef DEFAULT_DATA_STOREINTERFACE_H
#define DEFAULT_DATA_STOREINTERFACE_H
#include "default_data_store.hh"
using namespace saline;
#ifdef __cplusplus
extern "C" {
#endif
void Default_Data_Store_load(void * Default_Data_Store_ptr);
void* Default_Data_Store_initialize();
void Default_Data_Store_destroy(void * Default_Data_Store_ptr);
#ifdef __cplusplus
}
#endif
#endif /* DEFAULT_DATA_STOREINTERFACE_H */
