!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: Thu May 21 19:31:20 EDT 2020
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module default_data_store_M
use, intrinsic :: ISO_C_BINDING
use default_data_store_I
use Data_Store_M
type , extends(Data_Store) :: Default_Data_Store
    contains
    procedure, pass(this) :: initialize => Default_Data_Store_initialize
    procedure, pass(this) :: destroy => Default_Data_Store_destroy
end type Default_Data_Store
contains
subroutine Default_Data_Store_initialize(this)
    implicit none
    class(Default_Data_Store) :: this
    this%instance_ptr = f_Default_Data_Store_initialize()
end subroutine
subroutine Default_Data_Store_destroy(this)
    implicit none
    class(Default_Data_Store) :: this
    call f_Default_Data_Store_destroy(this%instance_ptr)
    this%instance_ptr = C_NULL_PTR
end subroutine
end module default_data_store_M
