/*!
* This file has been dynamically generated by Class Interface Xml (CIX) 
* DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
* If changes need to occur, modify the appropriate CIX xml file
* Date Generated: Tue Jun 14 14:36:27 EDT 2022
* If any issues are experiences with this generated file that cannot be fixed
* with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
*/
#include <string.h>
#include "default_data_storeInterface.h"
using namespace saline;
void Default_Data_Store_load(void * Default_Data_Store_ptr,char* path)
{
    ((Default_Data_Store*)Default_Data_Store_ptr)->load(path);
}

void* Default_Data_Store_initialize()
{
    return new Default_Data_Store();
}

void Default_Data_Store_destroy(void * Default_Data_Store_ptr)
{
    delete (Default_Data_Store*)Default_Data_Store_ptr;
}

