/*!
* This file has been dynamically generated by Class Interface Xml (CIX) 
* DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
* If changes need to occur, modify the appropriate CIX xml file
* Date Generated: Tue Jun 14 14:36:27 EDT 2022
* If any issues are experiences with this generated file that cannot be fixed
* with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
*/
#include <string.h>
#include "r_kister_data_storeInterface.h"
using namespace saline;
void R_Kister_Data_Store_load(void * R_Kister_Data_Store_ptr,char* path)
{
    ((R_Kister_Data_Store*)R_Kister_Data_Store_ptr)->load(path);
}

void* R_Kister_Data_Store_initialize()
{
    return new R_Kister_Data_Store();
}

void R_Kister_Data_Store_destroy(void * R_Kister_Data_Store_ptr)
{
    delete (R_Kister_Data_Store*)R_Kister_Data_Store_ptr;
}

