!>
!! This file has been dynamically generated by Class Interface Xml (CIX) 
!! DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
!! If changes need to occur, modify the appropriate CIX xml file
!! Date Generated: Thu May 21 19:31:20 EDT 2020
!! If any issues are experiences with this generated file that cannot be fixed
!! with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
!!/
module thermophysical_properties_M
use, intrinsic :: ISO_C_BINDING
use thermophysical_properties_I
use Data_Store_M
type Thermophysical_Properties
    type(C_PTR) :: instance_ptr=C_NULL_PTR
    contains
    procedure, pass(this) :: cp => Thermophysical_Properties_cp
    procedure, pass(this) :: cp_h => Thermophysical_Properties_cp_h
    procedure, pass(this) :: mu => Thermophysical_Properties_mu
    procedure, pass(this) :: mu_h => Thermophysical_Properties_mu_h
    procedure, pass(this) :: k => Thermophysical_Properties_k
    procedure, pass(this) :: k_h => Thermophysical_Properties_k_h
    procedure, pass(this) :: rho => Thermophysical_Properties_rho
    procedure, pass(this) :: rho_h => Thermophysical_Properties_rho_h
    procedure, pass(this) :: init_data_store => Thermophysical_Properties_init_data_store
    procedure, pass(this) :: set_composition => Thermophysical_Properties_set_composition
    procedure, pass(this) :: initialize => Thermophysical_Properties_initialize
    procedure, pass(this) :: destroy => Thermophysical_Properties_destroy
end type Thermophysical_Properties
contains
function Thermophysical_Properties_cp(this, t, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::t
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_cp(this%instance_ptr, t,p)
end function
function Thermophysical_Properties_cp_h(this, h, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::h
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_cp_h(this%instance_ptr, h,p)
end function
function Thermophysical_Properties_mu(this, t, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::t
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_mu(this%instance_ptr, t,p)
end function
function Thermophysical_Properties_mu_h(this, h, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::h
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_mu_h(this%instance_ptr, h,p)
end function
function Thermophysical_Properties_k(this, t, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::t
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_k(this%instance_ptr, t,p)
end function
function Thermophysical_Properties_k_h(this, h, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::h
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_k_h(this%instance_ptr, h,p)
end function
function Thermophysical_Properties_rho(this, t, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::t
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_rho(this%instance_ptr, t,p)
end function
function Thermophysical_Properties_rho_h(this, h, p) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    real(C_DOUBLE)::h
    real(C_DOUBLE)::p
    real(C_DOUBLE):: result2Return
    result2Return=f_Thermophysical_Properties_rho_h(this%instance_ptr, h,p)
end function
subroutine Thermophysical_Properties_init_data_store(this, data)
    implicit none
    class(Thermophysical_Properties)::this
    class(Data_Store)::data
    call f_Thermophysical_Properties_init_data_store(this%instance_ptr, data%instance_ptr)
end subroutine
function Thermophysical_Properties_set_composition(this, name, mole_perecents, count) result(result2Return)
    implicit none
    class(Thermophysical_Properties)::this
    character(len=*)::name
    real(C_DOUBLE), dimension(:)::mole_perecents
    integer(C_INT)::count
    logical(C_BOOL):: result2Return
    result2Return=f_Thermophysical_Properties_set_composition(this%instance_ptr, name//C_NULL_CHAR,mole_perecents(1),count)
end function
subroutine Thermophysical_Properties_initialize(this)
    implicit none
    class(Thermophysical_Properties) :: this
    this%instance_ptr = f_Thermophysical_Properties_initialize()
end subroutine
subroutine Thermophysical_Properties_destroy(this)
    implicit none
    class(Thermophysical_Properties) :: this
    call f_Thermophysical_Properties_destroy(this%instance_ptr)
    this%instance_ptr = C_NULL_PTR
end subroutine
end module thermophysical_properties_M
