/*!
* This file has been dynamically generated by Class Interface Xml (CIX) 
* DO NOT MODIFY THIS FILE -- CHANGES WILL BE OVERWRITTEN UPON REGENERATION
* If changes need to occur, modify the appropriate CIX xml file
* Date Generated: Thu May 21 19:31:20 EDT 2020
* If any issues are experiences with this generated file that cannot be fixed
* with adjustment of the CIX xml file, please contact Robert A. Lefebvre, raq@ornl.gov
*/
#include <string.h>
#include "thermophysical_propertiesInterface.h"
using namespace saline;
double Thermophysical_Properties_cp(void * Thermophysical_Properties_ptr,double * t,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->cp(*t,*p);
}

double Thermophysical_Properties_cp_h(void * Thermophysical_Properties_ptr,double * h,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->cp_h(*h,*p);
}

double Thermophysical_Properties_mu(void * Thermophysical_Properties_ptr,double * t,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->mu(*t,*p);
}

double Thermophysical_Properties_mu_h(void * Thermophysical_Properties_ptr,double * h,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->mu_h(*h,*p);
}

double Thermophysical_Properties_k(void * Thermophysical_Properties_ptr,double * t,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->k(*t,*p);
}

double Thermophysical_Properties_k_h(void * Thermophysical_Properties_ptr,double * h,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->k_h(*h,*p);
}

double Thermophysical_Properties_rho(void * Thermophysical_Properties_ptr,double * t,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->rho(*t,*p);
}

double Thermophysical_Properties_rho_h(void * Thermophysical_Properties_ptr,double * h,double * p)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->rho_h(*h,*p);
}

void Thermophysical_Properties_init_data_store(void * Thermophysical_Properties_ptr,Data_Store* data)
{
    ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->initialize(data);
}

bool Thermophysical_Properties_set_composition(void * Thermophysical_Properties_ptr,char* name,double* mole_perecents,int * count)
{
    return ((Thermophysical_Properties*)Thermophysical_Properties_ptr)->setComposition(name,mole_perecents,*count);
}

void* Thermophysical_Properties_initialize()
{
    return new Thermophysical_Properties();
}

void Thermophysical_Properties_destroy(void * Thermophysical_Properties_ptr)
{
    delete (Thermophysical_Properties*)Thermophysical_Properties_ptr;
}

